### ISSUE TITLE
Better jest integration

### ISSUE THREAD

**Issue by supersonicclay** [fusionjs/fusion-test-utils#160]
### Type of issue

Feature request

### Description

Currently jest's `test` is wrapped, but none of the other jest functions seem to be. Users should be able to use the following:

* `describe`
* `beforeEach`
* `afterEach`
* `beforeAll`
* `afterAll`

### Your environment

* fusion-test-utils version: 1.2.1

* Node.js version (`node --version`): v8.11.3

* npm version (`npm --version`): 5.6.0

* Operating System: OSX

**Comment by KevinGrandon** [comment]
Hello, thanks for filing this issue. You can actually use all of these methods as globals as we're still just running jest, so all standard jest syntax is supported. Please let us know if you have any problems using describe() today.

We are currently evaluating using *just* jest in the future, and are tracking that here: https://github.com/fusionjs/fusion-cli/issues/337 We will probably re-evaluate our recommended test API and assertions at the same time.

**Comment by supersonicclay** [comment]
That'd be great. Thanks!
